// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytixobtjzdqmryolhssd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aXhvYnRqemRxbXJ5b2xoc3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTY3NTcsImV4cCI6MjA2NTM3Mjc1N30.qFILGVdylg-_VwLTX0MfVuwGvKE2zJx8wp2x2lbNxPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);